<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="25868" started-at="2022-07-06T16:58:16Z" finished-at="2022-07-06T16:58:42Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="25868" started-at="2022-07-06T16:58:16Z" finished-at="2022-07-06T16:58:42Z">
      <class name="com.orangehrm.tests.LoginTests">
        <test-method status="PASS" signature="startReport()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="startReport" is-config="true" duration-ms="252" started-at="2022-07-06T16:58:16Z" finished-at="2022-07-06T16:58:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="setUp" is-config="true" duration-ms="16654" started-at="2022-07-06T16:58:16Z" finished-at="2022-07-06T16:58:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="m1()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="m1" duration-ms="23" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.orangehrm.tests.LoginTests.m1(LoginTests.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="getResult" is-config="true" duration-ms="16" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=m1 status=FAILURE method=LoginTests.m1()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="m2()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="m2" duration-ms="5" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: test
at com.orangehrm.tests.LoginTests.m2(LoginTests.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="getResult" is-config="true" duration-ms="0" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=m2 status=SKIP method=LoginTests.m2()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="m3()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="m3" duration-ms="2" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.orangehrm.tests.LoginTests.m3(LoginTests.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="PASS" signature="m4()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="m4" duration-ms="11" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m4 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="getResult" is-config="true" duration-ms="0" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=m3 status=FAILURE method=LoginTests.m3()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="getResult" is-config="true" duration-ms="1" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=m4 status=SUCCESS method=LoginTests.m4()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="m5()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="m5" duration-ms="6" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m5 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="getResult" is-config="true" duration-ms="2" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=m5 status=SUCCESS method=LoginTests.m5()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="verifyLogin()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="verifyLogin" duration-ms="2225" started-at="2022-07-06T16:58:33Z" finished-at="2022-07-06T16:58:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="getResult" is-config="true" duration-ms="1" started-at="2022-07-06T16:58:35Z" finished-at="2022-07-06T16:58:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLogin status=SUCCESS method=LoginTests.verifyLogin()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="tearDown" is-config="true" duration-ms="6865" started-at="2022-07-06T16:58:35Z" finished-at="2022-07-06T16:58:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.orangehrm.tests.LoginTests@78b66d36]" name="endReport" is-config="true" duration-ms="573" started-at="2022-07-06T16:58:42Z" finished-at="2022-07-06T16:58:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.orangehrm.tests.LoginTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
